# ========== 数据库配置 ==========
db_url: "sqlite:///test_database/flight_2/flight_2.sqlite"
max_tokens: 60000
temperature: 0.2
model_path: "defog/sqlcoder-7b-2"

database:
  root_path: "test_database"
  tables_json_path: "test/tables.json"

# ========== GraphRAG 配置 ==========
graphrag:
  enabled: True  
  tables_json_path: "test/tables.json"
  use_full_schema_fallback: true  
  top_k_tables: 5  
  use_full_schema : false