# db_url: "postgresql+psycopg2://test:test123@localhost:5432/academic"
db_url: "sqlite:///test_database/customers_and_orders/customers_and_orders.sqlite"
max_tokens: 20000
temperature: 0.2
model_path: "defog/sqlcoder-7b-2"